name: Build

on: push

jobs:
  build-n-publish:
    name: Build and publish Python distributions to PyPI and TestPyPI
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install .
        python -m pip install codecov pytest-cov
    - name: Run pytest
      run: |
        pytest tests/ --cov=autorank/ --cov-report=xml
    - name: Install setuptools
      run: |
        python -m pip install setuptools wheel
    - name: Build a binary wheel and a source tarball
      run: >-
        python setup.py sdist bdist_wheel
    - name: Publish to codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Build documentation
      run: |
        python -m pip install pydoc-markdown
        mkdir docs
        mkdir docs/examples
        cp examples/* docs/examples/
        cp flowchart.png docs/
        pydocmd build
    - name: Publish documentation of master on gh-pages
      uses: peaceiris/actions-gh-pages@v2.3.1
      env:
        PERSONAL_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: _build/site
    - name: Publish distribution to PyPI
      if: startsWith(github.event.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.pypi_password }}
